version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto21
    commands:
      - echo "Installing Maven..."

  build:
    commands:
      - echo "Building Spring Boot application..."
      - mvn clean install -DskipTests

      - echo "Listing target directory contents..."
      - ls -lh target/

      - echo "Listing only JAR files..."
      - ls -lh target/*.jar

      - echo "Copying JAR to root level for Elastic Beanstalk..."
      - cp target/*.jar application.jar

artifacts:
  files:
    - application.jar

cache:
  paths:
    - /root/.m2/**/*
